# Generated by Django 3.0.7 on 2020-07-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('txn', models.TextField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
